### PR TITLE
Replace 28MB GIF file with a 3MB video

### PR DESCRIPTION
**Pull request by niutech**
Please save users' data plans and loading times!

### CODE REVIEW

**Comment by alokmenghrajani** [comment]
Sure. But I'd rather you include the file in the repo (i.e. add it to the /files/2018/bootable_cd_retro_game_tweet/ folder and remove the existing gif).

**Comment by alokmenghrajani** [comment]
You still have to update the html to use the file you uploaded. Also worth deleting the old gif, since it won't be referenced anywhere.

**Comment by niutech** [comment]
I've done it right now.

**Comment by alokmenghrajani** [comment]
👍

**Comment by niutech** [comment]
It is weird, but the GIF fallback is still being downloaded despite the MP4 video. I will make another PR.

**Pull request merged**
